package com.example.fitnessnation;

import androidx.annotation.NonNull;
import androidx.room.ColumnInfo;
import androidx.room.Entity;
import androidx.room.PrimaryKey;

import java.io.Serializable;

@Entity(tableName = "meals")
public class Meal  implements Serializable {//serializable is for passing the object to the next activity

    public Meal(String name,String type, int imagePath, int calorie, String description, boolean choice) {
        this.name=name;
        this.imagePath = imagePath;
        this.calorie = calorie;
        this.description = description;
        this.type=type;
        this.choice=choice;
    }

    @PrimaryKey
    @NonNull

    @ColumnInfo(name = "meal_name")
    private String name;

    @ColumnInfo(name = "meal_type")
    private String type;

    @ColumnInfo(name = "meal_image")
    private int imagePath;

    @ColumnInfo(name = "meal_calorie")
    private int calorie=0;

    @ColumnInfo(name = "meal_choice")
    private boolean choice;//false equal weight loss, true equal weight gain

    @ColumnInfo(name = "meal_description")
    private String description;



    public String getName() { return name; }
    public String getType() { return type; }
    public int getImagePath() {
        return imagePath;
    }
    public int getCalorie() { return calorie; }
    public boolean getChoice() { return choice; }
    public String getDescription() {return description; }


    public void setName(String name) {
        this.name = name;
    }
    public void setType(String type) {
        this.type = type;
    }
    public void setImagePath(int imagePath) {this.imagePath=imagePath; }
    public void setCalorie(int calorie) {this.calorie=calorie; }
    public void setDescription(String description) { this.description = description; }
    public void setChoice(boolean choice) { this.choice=choice; }

    public static Meal[] populateData() {
        return new Meal[] {
               /* new Meal("Grapefruit","Breakfast" ,R.drawable.grapefruitjpg,52,"Grapefruits are low in calories, high in water and rich in fiber. Studies show that they may increase weight loss and reduce calorie intake and body fat. TO DO: However, if you are taking any drugs make sure to consult your doctor or pharmacist before eating grapefruit. Certain drugs may interact with grapefruit, potentially causing some adverse effects.", false),
                new Meal("Vegan Tacos", "Breakfast",R.drawable.vegan_tacos,245,"Preheat oven to 400 degrees F (204 C). Pat dry chickpeas with paper towels then mix with the rest of the “Bacon” Chickpea ingredients. Spread onto half of a parchment paper-lined baking sheet. Toss together Roasted Tomato ingredients and spread onto the other half. Bake for 20 minutes, or until chickpeas are crispy and tomatoes have burst. Scrambled Tofu: Meanwhile, add all Tofu ingredients to a large greased or non-stick skillet and roughly break up tofu with a spatula. Set over medium heat and cook until tofu begins to brown slightly, stirring often. Assemble: Spoon scrambled tofu, chickpeas, and tomatoes evenly onto tortillas. Garnish with your favorite.", false),
                new Meal("Shakshuka", "Breakfast",R.drawable.shakshuka,165,"Preheat oven to 375°F (190°C). Heat oil in an oven-safe skillet over medium heat, then add onion, garlic, and bell pepper. Cook until softened, about 5 minutes. Tomato: Add canned tomatoes, gently mashing them with a fork if needed to form a chunky sauce. Allow tomatoes to simmer, uncovered, until a thick sauce develops, 10 to 15 minutes. Stir in spices, salt, and pepper. Taste and adjust seasonings as needed. Eggs: Using the back of a spoon, form a few holes in the tomato mixture. Crack an egg into each hole (use as many eggs as you want). Bake: Transfer skillet to a preheated oven and cook, uncovered, for 8 to 12 minutes, or until egg whites are mostly cooked. They should be white and still a little jiggly (they'll continue to cook some after removing from the oven). Serve immediately, topped with crumbled feta, herbs, and bread for dipping.", false),
                new Meal("Crispy Hash Browns", "Breakfast",R.drawable.crispyhashbrowns,211,"Scrub the potatoes clean and grate them on a large-holed cheese grater (I left the skin on, but you can peel it first if you’d like). In a fine-mesh sieve, rinse the grated potato well until the water runs clear. Drain the potatoes, and then place them potato on a clean tea towel or  several paper towels. Twist the towel to remove as much moisture from the potatoes as possible (you might need to do this in two batches). Transfer the grated potato to a bowl and toss it with the salt, garlic powder and onion powder. In a large skillet (preferably cast iron, but non-stick works, too), warm the olive oil over medium heat until shimmering and a piece of grated potato sizzles on contact. Spread the potatoes over the skillet in an even layer and press them down with a spatula. Let them cook, undisturbed, for 2 minutes. Stir again, press them down again, and cook for another 2 minutes. Repeat in 2-minute intervals, flipping in sections once they’re crispy enough to do so, until the potatoes are golden brown and crispy, about 4 to 8 more minutes. Meanwhile, line a plate with a couple of layers of paper towels to absorb excess oil, and set it near the stove. Transfer the hash browns to the lined plate and let them drain for a minute. Season to cheese grater (I left the skin on, but you can peel it first if you’d like). In a fine-mesh sieve, rinse the grated potato well until the water runs clear. Drain the potatoes, and then place them potato on a clean tea towel or  several paper towels. Twist the towel to remove as much moisture from the potatoes as possible (you might need to do this in two batches). ", false),
                new Meal("Bircher Muesli ", "Breakfast",R.drawable.birchermuesli,409,"- In a bowl combine the oats, raisins, cinnamon, nut butter and applesauce. Stir to combine. Then add the milk and stir to combine. Grate half of the apple, then stir the grated apple into the oatmeal. Place the lid on the jar and refrigerate for at least 30 minutes, or up to 5 days. When you’re ready to serve, chop the remaining half on the apple into matchsticks. Top the oatmeal with the fresh apple, a splash of milk and/or a drizzle of honey (both optional).", false),
                new Meal("Tropical Acai Bowl ", "Breakfast",R.drawable.tropical_acai_bowl,257,"- In a blender, combine the frozen mango, pineapple and banana. Run the açai packets under warm water for about 10 seconds to let them thaw a bit, then cut them open and pour the açai pulp into the blender. Pour in the cold water, securely fasten the lid, and start blending ", false),
                new Meal("Egg, tomato and scallion sandwich ", "Breakfast",R.drawable.eggtomatoscallionsandwich,213,"Assemble the sandwich by placing the egg on the bread, then the tomato, then scallion. Top with salt and pepper and spread mayonnaise on the top of the bread.", false),
                new Meal("Healthy Bacon, Egg, and Potato Breakfast Casserole ", "Breakfast",R.drawable.baconeggpotatocasserole,184,"- Preheat oven to 375 degrees. Heat oil in a large skillet and sauté onion, bell pepper, mushrooms, garlic, bacon and Fines Herbs until onions are translucent. Set aside. In large bowl, whisk together eggs, cottage cheese and cheddar cheese. Stir in shredded potatoes. Add sautéed bacon and vegetables. Spoon into lightly greased 9x9 square dish. Bake 45 minutes until casserole is firm. Serve on bed of baby kale.", false),
                new Meal("Asian Sesame Zucchini Noodles ", "Lunch",R.drawable.asiansesamezucchininoodles,85,"In a large bowl, whisk cilantro, vinegar, oil, garlic, red pepper, sugar, and 1/2 teaspoon salt. Add zucchini; toss until well-combined. Serve immediately.", false),
                new Meal("Butternut Squash and White Bean Soup ", "Lunch",R.drawable.scrambled_eggs_veggies,260,"Cut neck off butternut squash (reserve base for another use). Peel and cut into 1/2-inch pieces. Heat 1 tablespoon olive oil in nonstick skillet on medium. Add the squash and cook, covered, stirring occasionally, 8 minutes. Meanwhile, heat remaining oil in Dutch oven on medium. Add onion and cook, covered, stirring occasionally, 6 minutes. Stir in garlic and ginger and cook 1 minute. Add broth, thyme and butternut squash and bring to a boil. Using a fork, mash white beans and add to soup along with chickpeas. Cook couscous as label directs; fluff with fork and fold in pistachios, apricots, cilantro and scallion. Serve soup topped with couscous mixture.", false),
                new Meal("Vegetable Ramen with Mushrooms and Bok Choy h ", "Lunch",R.drawable.vegetableramen,300,"Slice white parts of scallions and place in large pot with ginger and 8 cups water; bring to a boil. Stir in tamari, then add noodles and cook per package directions, adding mushrooms and bok choy 3 minutes after adding noodles. Remove from heat and stir in snow peas and vinegar. Divide soup among 4 bowls and place 1 egg half on top of each. Slice remaining scallion greens and serve over soup along with cilantro and red chili.", false),
                new Meal("Tuna Poke Bowl  ", "Lunch",R.drawable.tunapokebowl,213,"- In large bowl, whisk together soy sauce, sesame oil, onion, scallions, and pinch salt. Toss with tuna and refrigerate until ready to use. In small bowl, toss cucumbers with vinegar, sugar, sesame seeds ,and pinch salt. Let stand 5 minutes. Serve tuna, marinated cucumbers, and avocado over rice if desired. Sprinkle with additional black sesame seeds if desired.", false),
                new Meal("Tomato-Quinoa Soup ", "Lunch",R.drawable.tomato,280,"Cook quinoa as label directs. In 4-quart saucepan, heat butter and oil on medium until butter melts. Add shallots, garlic, and fennel seeds. Cook 4 to 6 minutes, or until vegetables begin to soften, stirring occasionally. Add tomatoes and broth. Heat to simmering on high. Simmer 15 minutes, stirring occasionally. With immersion or regular blender, purée mixture until smooth. Reheat soup if necessary. In medium bowl, combine cooked quinoa, pepitas, chives, and red pepper. Serve soup topped with quinoa mixture.", false),
                new Meal("Roasted Salmon With Green Beans and Tomatoes ", "Lunch",R.drawable.roastedsalmon,330,"Heat oven to 425°F. On large rimmed baking sheet, toss garlic, beans, tomatoes, olives and anchovies (if using) with 1 tablespoon oil and 1/4 teaspoon pepper. Roast until vegetables are tender and beginning to brown, 12 to 15 minutes. Meanwhile, heat remaining tablespoon oil in large skillet over medium heat. Season salmon with 1/4 teaspoon each salt and pepper and cook until golden brown and opaque throughout, 4 to 5 minutes per side. Serve with vegetables and yogurt if desired", false),
                new Meal("Tomato, Peach, and Basil Salad ", "Lunch",R.drawable.tomatopeachbasilsalad,75,"- In small bowl, combine onion and vinegar with 1/4 teaspoon salt. Let sit 5 minutes. Cut tomatoes and peaches into wedges and arrange on platter. Stir oil into onion mixture and spoon over fruit, then sprinkle with basil, feta, and cracked black pepper.", false),
                new Meal("Creamy Gluten-Free Tomato Pasta ", "Dinner",R.drawable.creamytomatoglutenreepasta,353,"Sauté onions and garlic in 1 tbsp olive until fragrant, about 2 minutes. Cook your gluten free pasta, whisk together the mayo and egg yolk and Add this mix to your pasta. Then gently mix in the sautéed onion/garlic. Toss the pasta with the tomatoes, kosher salt and pepper.", false),
                new Meal("Sriracha Shredded Chicken Tacos ", "Dinner",R.drawable.srirachashreddedchickentacos,420,"Preheat oven to 375 degrees. Place the chicken breasts on a baking sheet and top with Sriracha. Bake for 30 minutes (or until they're fully cooked). While the chicken is baking, heat the tortillas up (optional). Top each tortilla with chopped red cabbage and chopped peppers. When the chicken has finished baking, shred it and place in the tortillas. Top each taco with feta cheese and a drizzle of lime.", false),
                new Meal("White Bean and Tuna Salad  ", "Dinner",R.drawable.whitebeantunasalad,300,"Bring a large pot of water to a boil. Add 1 tablespoon salt, then green beans, and cook until just tender, 3 to 4 minutes. Drain and rinse under cold water to cool. Meanwhile, in a blender, puree shallot, basil, oil, vinegar, and 1/2 teaspoon each salt and pepper until smooth. Transfer half of dressing to large bowl and toss with green beans. Fold in lettuce, white beans, and tuna and serve with remaining dressing and eggs.", false),
                new Meal("Baked Chicken with Mushrooms and Sweet Potato", "Dinner",R.drawable.chickenmushroomssweetpotato,382,"- In a 350°F oven, bake chicken, topped with mushrooms, chives, and oil, for 15 minutes. Microwave sweet potato for five to seven minutes.", false),
                new Meal("Creamy Healthy Chicken Enchilada Skillet ", "Dinner",R.drawable.creamyhealthychickenenchiladaskillet,353,"- Combine the chicken and enchilada sauce in a skillet over medium-high heat. Stir, then add in the black beans and diced peppers. Mix in the sour cream and corn tortilla pieces, continue to stir. Once everything is evenly hot, top the casserole with cheese and optional cilantro. Serve with avocado slices.", false),
                new Meal("One-Pot Basil Chicken Baked Ziti  ", "Dinner",R.drawable.potbasilchickenbakedziti,250,"Preheat oven to 375 degrees. Mix the shredded, cooked chicken, cooked penne, pasta sauce, and spinach together. Pour into a casserole dish or bakeware. Top with mozzarella (or also mix it in) and basil leaves (shredded or whole). Bake for 25-30 minutes.", false),
                new Meal("Chili Mango Zesty Quinoa Salad", "Dinner",R.drawable.chilimangozestyquinoasalad,180,"Cook the quinoa according to directions. While the quinoa is cooking, chop the spinach, slice the tomatoes, cut the mango and avocado. Once the quinoa has finished cooking, mix all of the ingredients together in a bowl except for the mango, chili powder, cayenne, and avocado. Top each salad with slices of avocado and mango, sprinkled with chili powder and cayenne.", false),
                new Meal("Gluten-Free Berry Fruit Pizza ", "Breakfast",R.drawable.glutenpizza,178,"Pre-heat oven to 350ºF. Place a piece of parchment paper on a baking sheet. In a bowl, combine the crust ingredients and mix. Once combined, transfer to the baking sheet. With hands, press dough to start forming into a rectangle shape. Then place another piece of parchment paper over top and with a rolling pin, roll until about 1/4-1/2 inch thick. You should end up with about a 10×8-inch rectangle. Bake crust for 16 minutes or until edges are golden brown. Remove from oven and let cool completely. Combine and mix together yogurt (or non-dairy option), maple syrup, and vanilla extract. Spread yogurt mixture over cooled crust and then top with berries. Add optional toppings if desired.",true),
                new Meal("Paleo Crepes Cake with Lemon Strawberry Coconut Cream " , "Breakfast",R.drawable.paleocrepes,237,"Pour a scant 1/4 cup (just under 1/4 cup, or 3.5 Tbsp) into the pre-heated pan and swirl around until the pan is evenly coated. Cook until the outsides of the crepe darken and the inside feels just set, this takes 4-6 minutes depending on your pan. Mine were perfect about 4.5 minutes. Very gently pick up the crepe and gently flip over. Cook until the other side is just set, only another 20-40 seconds, you don't want to dry them out! Repeat until all the batter is used, storing the crepes in the fridge on a plate as you cook them. You want them nice and cold when you put the cream on! You should end up with 17 crepes. To make the cream: Place the coconut cream, honey, lemon zest, lemon juice and vanilla extract into a large bowl. Using an electric hand mixer, beat until smooth and well combined, scraping the sides down as necessary. Set aside 1/4 cup of the cream for later use.",true),
                new Meal("Pancake Skewers with Hazelnut Meal, Bananas and Chocolate Dip", "Breakfast",R.drawable.bananahazelnutpancake,245,"Add in the mashed banana, processing again until the banana is incorporated. Drop pancake batter onto the heated griddle, using a 1/2 tbsp measuring spoon to measure. Slightly spread out with a spoon, but you want to keep the pancakes small. Cook until the outsides of the pancake are set and the underside is a deep golden brown, about 4-6 minutes. Gently flip and cook an additional 3-5 minutes on the other side. Repeat until the batter is gone, storing any pancakes in the preheated oven to keep warm until ready to serve. While the pancakes cook, you can make the chocolate sauce (this can also be made the day before.) In a small pot heat the cream and the honey together until just boiling. Remove from the heat and add in the chopped chocolate. Let the mixture stand for 30 seconds, and then whisk until the sauce is smooth and the chocolate is melted and mixed in.",true),
                new Meal("Spinach Parmesan Baked Eggs Recipe ", "Breakfast",R.drawable.spinachparmesanbakedeggs,149,"Preheat oven to 350 degrees. Spray an 8 inch by 8-inch casserole dish with nonstick spray. In a large skillet, heat the olive oil on medium heat. Once hot, add the spinach and garlic. Sauté until the spinach is wilted. Remove from heat and drain off any excess liquid. Stir in the parmesan cheese and spoon the mixture into an even layer in the casserole dish. Create four small divots in the spinach for the eggs. Crack an egg into each divot. Bake for 15 to 20 minutes or until the egg whites are mostly set. Remove from oven and let cool for about 5 minutes then sprinkle with the tomato.",true),
                new Meal("Hummus Breakfast Bowl ", "Breakfast",R.drawable.hummusbowl,354,"Heat the olive oil in a large skillet on medium heat. Once hot add the kale. Sauté the kale for 3-4 minutes then add in the tomatoes and peppers. Cook for another 4-5 minutes. Lightly beat the egg and slowly add the kale and peppers. Scramble until eggs are no longer runny. Place the rice or quinoa into the bottom of a serving bowl, top with the vegetables and egg. Spoon the hummus on top and sprinkle with sunflower seeds.",true),
                new Meal("White Bean Avocado Toast ", "Breakfast",R.drawable.whitebeantunasalad,298,"In a small bowl, combine the beans, tahini, half the lemon juice, and half the salt. Mash well. In a second bowl combine the avocado, remaining lemon juice and remaining salt. Lightly mash. Spread the mashed beans on to the toast. Spoon the avocado on top of the beans and top with tomatoes.",true),
                new Meal("Applesauce Muffins ", "Breakfast",R.drawable.applesaucemuffins,80,"Whisk all liquid ingredients together. Preheat oven to 350, and line a muffin tin. In a new bowl, stir remaining ingredients very well. Pour dry into wet, and stir until just evenly mixed. Fill each liner about 2/3 of the way, leaving a little room because they will rise. Bake on the center rack, 20 minutes or until muffins have domed and a toothpick inserted into the center of a muffin comes out mostly clean. Let cool. (If you loosely cover overnight on the counter or refrigerated, the liners peel off easily the next day and flavor and texture are even better.) Leftovers can be frozen if desired.",true),
                new Meal("Paleo Bars with Nuts and Chocolate Drizzle ", "Breakfast",R.drawable.paleonutbar,232,"Coconut Palm Sugar, Agave, vanilla extract, sea salt, and cinnamon in a large sauce pot. Bring to a simmer and stir to dissolve the sugar. The moment the sugar is completely melted, and the edges are bubbling, turn off the heat and pour in the nuts. Quickly mix the nuts into the syrup with a wooden spoon, until they are completely coated. Pour the nut mixture out onto the prepared baking sheet. Use a piece of wax paper to press the mixture firmly together. Bake the nut bars on the center rack for approximately 20 minutes until the tops are golden. Then (this is the hard part) allow the nut bars to cool for at least 45 minutes in the pan.",true),*/
                new Meal("Crispy Tofu Bowl", "Lunch",R.drawable.crispytofubowl,445,"Slice tofu 1/4 inch thick. Place on cutting board between paper towels; top with baking sheet. Top with large cans or other weight; let stand 10 minutes. Soak red onion in cold water. Whisk red wine vinegar and Thai sweet chili sauce, olive oil and 1/4 teaspoon salt. Pat onion dry; toss with half of vinaigrette and cucumber. Sprinkle tofu on both sides with cornstarch. In 12-inch skillet, heat vegetable oil on medium-high until hot. Carefully add tofu. Cook until deep golden brown, 2 to 3 minutes per side. Drain on paper towels. Divide quinoa among 4 bowls. Top each with salad, roasted cashew halves, parsley leaves and tofu.",true),
                new Meal("Creamy Lemon Chicken Pasta ", "Lunch",R.drawable.paleonutbar,232,"",true),
                new Meal("Korean Pineapple Beef Lettuce Wraps ", "Lunch",R.drawable.creamylemonchickenpasta,565,"Cook linguine per package directions, adding peas during the last 2 minutes of cooking. Reserve 1 cup pasta cooking liquid, then drain pasta and peas. Meanwhile, heat olive oil in large deep skillet on medium-high. Season chicken with kosher salt and pepper and cook until golden brown on all sides, 4 to 5 minutes. Add lemon juice to skillet and cook, scraping up any browned bits. Add cream cheese and stir until melted; remove from heat. Fold in lemon zest and Parmesan, then parsley. Toss with pasta (adding reserved cooking liquid, 1 tablespoon at a time as necessary).",true),
                new Meal("Pesto Pasta", "Lunch",R.drawable.pestopasta,376,"In medium bowl, combine pineapple juice, garlic, soy sauce, red pepper flakes, ginger, honey, and sesame oil. Thinly slice frozen meat, add to marinade and toss to coat. Let marinate 30 minutes or cover and refrigerate up to 3 hours. Remove from refrigerator 30 minutes before cooking. Heat large stainless-steel skillet on medium-high. Add 1 tablespoon canola oil. Transfer half of beef mixture to skillet, arrange in even layer, season with 1/4 teaspoon salt and cook without moving until lightly browned, 1 minute. Toss beef and continue to cook until just cooked through and crisp at edges, 2 minutes. Transfer to plate. Repeat with remaining tablespoon oil and beef. Serve immediately with lettuce leaves, sticky rice, scallions, chilis, and peanuts, if desired.",true),
                new Meal("Fried Avocado Tacos ", "Lunch",R.drawable.frieavocadoos,677,"In a small bowl, whisk together the flour and ¼ teaspoon each salt and pepper. Lightly beat the egg whites in a second small bowl. In a third small bowl, combine the panko with the oil. Cut the avocados in half, remove the pit and peel. Cut each half into ½-inch-thick slices. Working with one slice at a time, coat avocado slices lightly in flour, then in the egg, letting any excess drip off and finally in the panko, pressing gently to help it adhere. Transfer to the prepared baking sheet and repeat with remaining avocado slices. Bake until golden brown, 20 to 25 minutes. Meanwhile, finely grate the lime zest into a large bowl, then squeeze in 2 tablespoon juice. Whisk in the mayonnaise and a pinch of salt. Add the cabbage, scallions, and jalapeño and toss to coat; fold in the cilantro. Fill the tortillas with the avocados and top with the cabbage slaw. Serve with extra cilantro, lime wedges and sour cream, if desired.",true),
                new Meal("Curried Butternut Squash Stew ", "Lunch",R.drawable.curriedbutternutsquashstew,565,"- In bowl of a 6-quart slow cooker, whisk together coconut milk, vegetable bouillon base, curry powder, turmeric, cardamom, 1 tablespoon grated ginger, 4 cups water, and 1 teaspoon salt. Add split peas, tomatoes (and their juices), butternut squash, and onion and mix to combine. Cook, covered, until most of the liquid has been absorbed and lentils are tender, 6 to 7 hours on low or 41⁄2 to 5 hours on high. Make lemon-scallion drizzle: In a small bowl, whisk together olive oil, lemon juice and zest, scallions, remaining 2 tablespoon grated ginger, and 1⁄4 teaspoon salt. Serve the stew with rice and a dollop of yogurt, if desired. Drizzle with lemon-scallion drizzle.",true),
                new Meal("Rotisserie Chicken Cobb Salad ", "Lunch",R.drawable.rotisseriechickencobbsalad,456,"In large bowl, combine extra virgin olive oil and red wine vinegar with 1/2 teaspoon each salt and pepper. Stir in plum tomatoes. From rotisserie chicken, shred 3 cups meat. Stir into dressing along with avocado, bacon and crumbled blue cheese. Serve over 4 thick slices iceberg lettuce; top with grated hard-cooked egg.",true),
                new Meal("Paleo Chicken Mushroom Casserole ", "Dinner",R.drawable.paleochickenmushroomcasserole,456,"Preheat oven to 375 degrees. Bake the cubed chicken breasts until fully cooked (about 30 minutes). While the chicken is baking, heat up the avocado oil in a skillet over medium-high heat. Spiralize the zucchini. Cook the mushrooms in the oil for about 5 minutes. Add in the spiralized zucchini and continue to cook for another 7-10 minutes (or until the mushrooms reduce in size and the zucchini softens). In a separate bowl, mix the cashew butter and almond milk to create a sauce. Remove the chicken from the oven and place in the skillet. Pour the cashew butter and almond milk into the skillet. Top with optional grated vegan cheese and continue to cook until everything is hot.",true),
                new Meal("BBQ Chicken Power Bowls ", "Dinner",R.drawable.chicken,345,"- Preheat oven to 375 degrees. Cut each chicken breast in half (long-ways). Please the chicken on an oiled baking sheet and glaze with BBQ sauce. Bake for 30 minutes (or until fully cooked). While the chicken is baking, cook the rice according to directions. Toss the kale, red cabbage, and tahini. Place into bowls and top with the baked chicken and avocado.",true),
                new Meal("Rotisserie Chicken Cobb Salad ", "Dinner",R.drawable.rotisseriechickencobbsalad,456,"",true),
                new Meal("Meal Prep Black Bean Quinoa Bowls ", "Dinner",R.drawable.mealprep,345,"- Cook the quinoa according to directions. While the quinoa is cooking, sauté the spinach. Next, heat up the fajita veggies. Fill each meal prep container (or each bowl) with quinoa, black beans, corn, spinach, fajita veggies, corn, and avocado. ",true),
                new Meal("Spinach & Mushroom Naan Pizza ", "Dinner",R.drawable.pizza,341,"Preheat oven to 425 degrees. Top each naan bread with olive oil, spinach, cheese, and mushrooms. Garnish if desired. Place on a baking sheet and bake 15-20 minutes (or until cheese is melted).",true),





        };
    }

}
